### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by 123maxm** [AJS-development/OAPlugins#3]
Possibly add a client so you can play it on your own website?

**Comment by segg21** [comment]
@123maxm not gonna happen. We got other options in the future, but you're not allowed to get client files, since it's our content,and privacy.

**Comment by 123maxm** [comment]
But then that's what this is missing, we used to love Ogar Unlimited because it was open source, we could do whatever you want with it, now it is all closed up....

**Comment by segg21** [comment]
@123maxm I'm sorry. But things won't work the same like old, but even better.

**Comment by segg21** [comment]
Think about having your own server, domain to client & server.

You'll be able to do certain things with the client with server settings (in the future).

We aren't even done with the client, therefor there is still wait before we do anything else with this project.
